name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [36, 37, 38, 39, 310]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install cibuildwheel
        run: |
          python -m pip install "cibuildwheel==2.1.3"
      
      - name: Build wheels
        run: |
          python itree/build_wheel.py --output-dir wheelhouse --python-version ${{ matrix.python-version}}

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
